# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentfund',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='policyoperation',
            name='operation_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='policyoperation',
            unique_together=set([('policy', 'operation_id')]),
        ),
    ]
