# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_policyoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyoperation',
            name='operation_amount',
            field=models.FloatField(default=0),
        ),
    ]
