# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-09 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20160413_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyOperationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_transfer', models.FloatField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.InvestmentFund')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PolicyOperation')),
            ],
        ),
    ]
