# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_policyoperation_operation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyoperation',
            name='operation_id',
            field=models.IntegerField(unique=True),
        ),
    ]
