# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapoint',
            old_name='pricedate',
            new_name='price_date',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='unitprice',
            new_name='unit_price',
        ),
        migrations.AlterField(
            model_name='investmentfund',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='datapoint',
            unique_together=set([('fund', 'price_date')]),
        ),
    ]
