# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raport', '0002_auto_20160312_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='price_date',
            field=models.DateField(),
        ),
    ]
